image: gradle:8.6.0-jdk21-alpine

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - apk add protoc
  script:
    - gradle clean build
  artifacts:
    paths:
      - "**/build/libs/*.jar"
    expire_in: 1 week

test:
  stage: test
  before_script:
    - apk add protoc
  script:
    - gradle check
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/TEST-*.xml"
      coverage_report:
        coverage_format: cobertura
        path: "**/build/reports/jacoco/test/cobertura-jacocoTestReport.xml"