image: gradle:8.6.0-jdk21-alpine

stages:
  - build
  - test

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  before_script:
    - apk add protoc
  script:
    - gradle clean build
  artifacts:
    paths:
      - "**/build/distributions/cirrina-*.zip"
      - "**/build/generated/source/proto/main/*"
    expire_in: 1 week

docker-build-main:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: '$CI_REPOSITORY == "upstream" && $CI_COMMIT_REF_NAME == "main"'

docker-build-develop:
  image: docker:latest
  stage: build
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  rules:
    - if: '$CI_REPOSITORY == "upstream" && $CI_COMMIT_REF_NAME == "develop"'

test:
  stage: test
  before_script:
    - apk add protoc
  script:
    - gradle check
  artifacts:
    when: always
    reports:
      junit: "**/build/test-results/test/TEST-*.xml"
      coverage_report:
        coverage_format: cobertura
        path: "**/build/reports/jacoco/test/cobertura-jacocoTestReport.xml"
